CP 92 Add Participant property to PhoneCallFacet
ucoProject/UCO pull request #325
Opened 2021-12-15 18:34 UTC by kchason

2022-02-08 18:51 UTC, ajnelson-nist requested changes

2022-02-08 18:51 UTC, ajnelson-nist commented on ontology/observable/observable.ttl
> +	rdfs:comment "A call facet is a connection as part of a realtime cyber communication between one or more parties."@en ;
There's a copy-paste error here - `s/call facet/call/`.

2022-02-08 18:55 UTC, ajnelson-nist approved these changes

2022-02-08 18:55 UTC, ajnelson-nist commented
This is ready for a Solutions Approval vote, to my eye.

2022-02-22 17:14 UTC, b0bkaT approved these changes

2022-02-22 17:14 UTC, merged